export const SELECT_ROW = 'SELECT_ROW';
export const CHANGE_SORT = 'CHANGE_SORT';
export const DESELECT_ROW = 'DESELECT_ROW';
export const SORT_CHANGE = 'SORT_CHANGE';
export const COLUMN_ORDER_CHANGE = 'COLUMN_ORDER_CHANGE';
export const COLUMN_RESIZE_CHANGE = 'COLUMN_RESIZE_CHANGE';
export const COLUMN_VISIBILITY_CHANGE = 'COLUMN_VISIBILITY_CHANGE';
export const SELECT_ROWS = 'SELECT_ROWS';
export const DESELECT_ROWS = 'DESELECT_ROWS';
export const SCROLL_CHANGE = 'SCROLL_CHANGE';

